baseURL = "https://hugo-netlifycms-test-site.netlify.app/"
languageCode = "en-us"
title = "PermissionCenterWebpart Documentation"
theme = "Learn"

[params]
  themeVariant = "whizzy"


[outputs]
    home = [ "HTML", "RSS", "JSON"]

[markup]
  defaultMarkdownHandler = "goldmark"

  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = false
    [markup.goldmark.parser]
      autoHeadingID = true
      autoHeadingIDType = "github"
      [markup.goldmark.parser.attribute]
        block = false
        title = true
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = false
      xhtml = false